// TEMPORARY: Using mock news API for development without backend
// TODO: Replace with real API calls when backend is ready
console.warn('🚨 USING MOCK NEWS API - FOR DEVELOPMENT ONLY');

const API_BASE_URL = process.env.REACT_APP_API_URL || 'http://localhost:5001';

// Simulate API delay
const simulateDelay = (ms = 1000) => new Promise(resolve => setTimeout(resolve, ms));

/**
 * Generate a balanced news article
 * @param {string} topicName - Topic to generate article about
 * @param {string} category - Category (Tech, Business, etc.)
 * @returns {Promise<Object>} Generated article
 */
export async function generateArticle(topicName, category = 'General') {
  console.log('Mock generateArticle called with:', { topicName, category });
  
  // Simulate API delay
  await simulateDelay(1500);
  
  // Return mock article
  return {
    id: `article-${Date.now()}`,
    title: `Breaking: ${topicName} - ${category} News`,
    content: `This is a mock article about ${topicName} in the ${category} category. In a real implementation, this would be generated by the backend API using AI to create balanced, fact-based reporting.`,
    category: category,
    timestamp: new Date().toISOString(),
    author: 'Mock News Generator',
    wordCount: 250,
    readingTime: '2 min read'
  };
}

/**
 * Get all articles, optionally filtered by category
 * @param {string} category - Category filter (optional)
 * @returns {Promise<Object>} Articles list
 */
export async function getArticles(category = null) {
  console.log('Mock getArticles called with category:', category);
  
  // Simulate API delay
  await simulateDelay(800);
  
  // Return mock articles
  const mockArticles = [
    {
      id: 'article-1',
      title: 'Tech Giant Announces Major AI Breakthrough',
      category: 'Technology',
      timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      author: 'Tech Reporter',
      wordCount: 450,
      readingTime: '3 min read'
    },
    {
      id: 'article-2',
      title: 'Climate Summit Reaches Historic Agreement',
      category: 'Environment',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
      author: 'Environmental Correspondent',
      wordCount: 380,
      readingTime: '2 min read'
    },
    {
      id: 'article-3',
      title: 'Economic Policy Changes Announced',
      category: 'Business',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
      author: 'Business Editor',
      wordCount: 520,
      readingTime: '4 min read'
    }
  ];
  
  const filteredArticles = category 
    ? mockArticles.filter(article => article.category === category)
    : mockArticles;
  
  return {
    articles: filteredArticles,
    total: filteredArticles.length,
    category: category || 'all'
  };
}

/**
 * Get a specific article by ID
 * @param {string} id - Article ID
 * @returns {Promise<Object>} Article data
 */
export async function getArticle(id) {
  console.log('Mock getArticle called with id:', id);
  
  // Simulate API delay
  await simulateDelay(600);
  
  // Return mock article
  return {
    id: id,
    title: `Mock Article: ${id}`,
    content: `This is a mock article with ID ${id}. In a real implementation, this would fetch the actual article content from the backend.`,
    category: 'General',
    timestamp: new Date().toISOString(),
    author: 'Mock Author',
    wordCount: 300,
    readingTime: '2 min read'
  };
}
